---
- name: Install apache httpd  (state=present is optional)
  hosts: sample-group
  become: true
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: ensure apache is running
  hosts: sample2-group
  service:
    name: apache2
    state: started

- name: Check ping
  ping:

- name: Download example.svg
  get_url:
    url: https://upload.wikimedia.org/wikipedia/commons/8/84/Example.svg
    dest: /etc/example.svg
    mode: '0440'
